language: bash
dist: jugg

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y nmap

before_script:
  - echo "Preparation stage"
  - image="gopeak/masterlab:socket"


script:
  - docker pull "$image"
  - docker run -d --name mlsocket -p 9002:9002 gopeak/masterlab:socket
  - nmap 127.0.0.1 -p 9002 | grep open

